#test.db:
#  schema: demo
#  url: jdbc:mysql://127.0.0.1:3307/weed3demo?useSSL=false&useUnicode=true&characterEncoding=utf8&useSSL=false
#  username: root
#  password: 123456
#  driverClassName: com.mysql.jdbc.Driver



# 适合 weed3 的配置
test.db:
  schema: rock
  url: jdbc:mysql://localdb:3306/rock?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  username: demo
  password: UL0hHlg0Ybq60xyb
  driverClassName: com.mysql.jdbc.Driver


# 适合 weed3 的配置（演示多数据源用）
test.db2:
  schema: rock
  url: jdbc:mysql://localdb:3306/rock?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  username: demo
  password: UL0hHlg0Ybq60xyb
  driverClassName: com.mysql.jdbc.Driver

# 适合 HikariCP 的配置
#test.db:
#  schema: rock
#  jdbcUrl: jdbc:mysql://localdb:3306/rock?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#  username: demo
#  password: UL0hHlg0Ybq60xyb
#  driverClassName: com.mysql.jdbc.Driver

